[[main]]
  name = "Guides"
  pageRef = "guides"
  weight = 10

[[main]]
  name = "Cities"
  pageRef = "cities"
  weight = 20

[[main]]
  name = "Recipes"
  pageRef = "recipes"
  weight = 30

[[main]]
  name = "Shop"
  pageRef = "shopping"
  weight = 40

[[main]]
  name = "About"
  pageRef = "about"
  weight = 50

[[footer]]
  name = "Guides"
  pageRef = "guides"
  weight = 10

[[footer]]
  name = "Cities"
  pageRef = "cities"
  weight = 20

[[footer]]
  name = "Recipes"
  pageRef = "recipes"
  weight = 30

[[footer]]
  name = "Shop"
  pageRef = "shopping"
  weight = 40

[[footer]]
  name = "About"
  pageRef = "about"
  weight = 50

[[footer]]
  name = "Privacy"
  pageRef = "privacy"
  weight = 60

[[footer]]
  name = "Affiliate Disclosure"
  pageRef = "affiliate-disclosure"
  weight = 70
