colorScheme = "ocean"
defaultAppearance = "light"
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true
enableStructuredBreadcrumbs = true

[header]
  layout = "basic"

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "page"
  showRecent = true
  showRecentItems = 8
  showMoreLink = false
  cardView = true
  cardViewScreenWidth = false

[article]
  showDate = true
  showDateUpdated = false
  showAuthor = false
  showHero = false
  showBreadcrumbs = true
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = true
  showCategories = true
  showTags = true
  showWordCount = true
  showPagination = true
  showRelatedContent = true
  relatedContentLimit = 3

[list]
  showBreadcrumbs = true
  showSummary = true
  showCards = true
  groupByYear = false
  cardView = true
  cardViewScreenWidth = false

[taxonomy]
  showTermCount = true
  cardView = true

[term]
  showBreadcrumbs = true
  cardView = true
  groupByYear = false

[sitemap]
  excludedKinds = ["taxonomy", "term"]

[seo]
  metaDescriptionOrder = ["description", "summary", "site"]
